_homepage:
    pattern:  /
    defaults: { _controller: DistribuceTiskuBundle:Page:index }
    requirements:   
        _method: GET
    
_about:    
    pattern:  /about
    defaults: { _controller: DistribuceTiskuBundle:Page:about }
    requirements:   
        _method: GET
        
_contact:    
    pattern:  /contact
    defaults: { _controller: DistribuceTiskuBundle:Page:contact }
    requirements:   
        _method: GET|POST       


_seznamTiskovin:    
    pattern:  /seznamTiskovin
    defaults: { _controller: DistribuceTiskuBundle:Page:seznamTiskovin }
    requirements:   
        _method: GET
        
_login:
    path:   /login
    defaults:  { _controller: DistribuceTiskuBundle:Security:login }

_login_check:
    path:   /login_check
    defaults:  { _controller: DistribuceTiskuBundle:Security:login_check }
    
_logout:
    path:   /logout
    defaults:  { _controller: DistribuceTiskuBundle:Security:logout }
    
_customerAdd:    
    pattern:  /customerAdd
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerAdd }
    requirements:   
        _method: GET|POST
        
_customerEdit:    
    pattern:  /customerEdit
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerEdit }
    requirements:   
        _method: GET|POST

_customerRemove:    
    pattern:  /customerRemove
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerRemove }
    requirements:   
        _method: GET|POST    
        
_customerRemoveById:    
    pattern:  /customerRemoveById/{id}
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerRemove }
    requirements:   
        _method: GET|POST        

_customerList:    
    pattern:  /customerList
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerList }
    requirements:   
        _method: GET|POST    
        
_bookAdd:    
    pattern:  /bookAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:bookAdd }
    requirements:   
        _method: GET|POST

_bookEdit:
    pattern:  /bookEdit
    defaults: { _controller: DistribuceTiskuBundle:Form:bookEdit }
    requirements:   
        _method: GET|POST
        
_bookRemove:
    pattern:  /bookRemove
    defaults: { _controller: DistribuceTiskuBundle:Form:bookRemove }
    requirements:   
        _method: GET|POST    
    
_supplierAdd:    
    pattern:  /supplierAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:supplieradd }
    requirements:   
        _method: GET|POST

_supplierEdit:    
    pattern:  /supplierEdit
    defaults: { _controller: DistribuceTiskuBundle:Form:supplierEdit }
    requirements:   
        _method: GET|POST

_supplierRemove:    
    pattern:  /supplierRemove
    defaults: { _controller: DistribuceTiskuBundle:Form:supplierRemove }
    requirements:   
        _method: GET|POST
        
_subscriptionAdd:    
    pattern:  /subscriptionAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionadd }
    requirements:   
        _method: GET|POST

_subscriptionEdit:    
    pattern:  /subscriptionEdit
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionEdit }
    requirements:   
        _method: GET|POST
        
_subscriptionRemove:    
    pattern:  /subscriptionAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionRemove }
    requirements:   
        _method: GET|POST 
        
_subscription:    
    pattern:  /subscription
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionadd }
    requirements:   
        _method: GET|POST
        
_subscriptionInteruptionAdd:    
    pattern:  /subscriptionInteruptionAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionInteruptionadd }
    requirements:   
        _method: GET|POST
        
_profile:    
    pattern:  /profile
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionInteruptionadd }
    requirements:   
        _method: GET|POST        