_homepage:
    pattern:  /
    defaults: { _controller: DistribuceTiskuBundle:Page:index }
    requirements:   
        _method: GET
    
_about:    
    pattern:  /about
    defaults: { _controller: DistribuceTiskuBundle:Page:about }
    requirements:   
        _method: GET
        
_contact:    
    pattern:  /contact
    defaults: { _controller: DistribuceTiskuBundle:Page:contact }
    requirements:   
        _method: GET|POST       


_seznamTiskovin:    
    pattern:  /seznamTiskovin
    defaults: { _controller: DistribuceTiskuBundle:Page:seznamTiskovin }
    requirements:   
        _method: GET
        
_login:
    path:   /login
    defaults:  { _controller: DistribuceTiskuBundle:Security:login }

_login_check:
    path:   /login_check
    defaults:  { _controller: DistribuceTiskuBundle:Security:login_check }
    
_logout:
    path:   /logout
    defaults:  { _controller: DistribuceTiskuBundle:Security:logout }
    
_customerAdd:    
    pattern:  /customerAdd
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerAdd }
    requirements:   
        _method: GET|POST
        
_customerEdit:    
    pattern:  /customerEdit
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerEdit }
    requirements:   
        _method: GET|POST

_customerEditById:    
    pattern:  /customerEditById/{id}
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerEditById }
    requirements:   
        _method: GET|POST 
        
_customerEditByName:    
    pattern:  /customerEditByName/{name}
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerEditByName }
    requirements:   
        _method: GET|POST           

_customerRemove:    
    pattern:  /customerRemove
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerRemove }
    requirements:   
        _method: GET|POST    
        
_customerRemoveById:    
    pattern:  /customerRemoveById/{id}
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerRemoveById }
    requirements:   
        _method: GET|POST        

_customerList:    
    pattern:  /customerList
    defaults: { _controller: DistribuceTiskuBundle:Customer:customerList }
    requirements:   
        _method: GET|POST    
        
_bookAdd:    
    pattern:  /bookAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:bookAdd }
    requirements:   
        _method: GET|POST

_bookEdit:
    pattern:  /bookEdit/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:bookEdit }
    requirements:   
        _method: GET|POST

_bookList:
    pattern:  /bookList
    defaults: { _controller: DistribuceTiskuBundle:Form:bookList }
    requirements:   
        _method: GET|POST        
         
_ubookList:
    pattern:  /ubookList
    defaults: { _controller: DistribuceTiskuBundle:Form:ubookList }
    requirements:   
        _method: GET|POST  
        
    
_supplierAdd:    
    pattern:  /supplierAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:supplieradd }
    requirements:   
        _method: GET|POST

_supplierEdit:    
    pattern:  /supplierEdit/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:supplierEdit }
    requirements:   
        _method: GET|POST

_supplierDelete:    
    pattern:  /supplierDelete/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:supplierDelete }
    requirements:   
        _method: GET|POST

_supplierList:    
    pattern:  /supplierList
    defaults: { _controller: DistribuceTiskuBundle:Form:supplierList }
    requirements:   
        _method: GET|POST
        
_subscriptionAdd:    
    pattern:  /subscriptionAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionAdd }
    requirements:   
        _method: GET|POST

_usubscriptionAdd:    
    pattern:  /usubscriptionAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:usubscriptionAdd }
    requirements:   
        _method: GET|POST
        
_subscriptionEdit:    
    pattern:  /subscriptionEdit/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionEdit }
    requirements:   
        _method: GET|POST
        
_subscriptionRemove:    
    pattern:  /subscriptionRemove/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionRemove }
    requirements:   
        _method: GET|POST 
        
_subscription:    
    pattern:  /subscription
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionadd }
    requirements:   
        _method: GET|POST
        
_subscriptionList:    
    pattern:  /subscriptionList
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionList }
    requirements:   
        _method: GET|POST

_usubscriptionList:    
    pattern:  /usubscriptionList
    defaults: { _controller: DistribuceTiskuBundle:Form:usubscriptionList }
    requirements:   
        _method: GET|POST
        
_usubscriptionEdit:    
    pattern:  /usubscriptionEdit/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:usubscriptionEdit }
    requirements:   
        _method: GET|POST
        
_subscriptionInterruption:    
    pattern:  /subscriptionInterruption/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionInterruption }
    requirements:   
        _method: GET|POST
        
_subscriptionInterruptionList:    
    pattern:  /subscriptionInterruptionList/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionInterruptionList }
    requirements:   
        _method: GET|POST
        
_subscriptionInteruptionDelete:    
    pattern:  /subscriptionInteruptionDelete/{id}
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionInteruptionDelete }
    requirements:   
        _method: GET|POST
        
_profile:    
    pattern:  /profile
    defaults: { _controller: DistribuceTiskuBundle:Customer:profile }
    requirements:   
        _method: GET|POST     
