_homepage:
    pattern:  /
    defaults: { _controller: DistribuceTiskuBundle:Page:index }
    requirements:   
        _method: GET
    
_about:    
    pattern:  /about
    defaults: { _controller: DistribuceTiskuBundle:Page:about }
    requirements:   
        _method: GET
        
_contact:    
    pattern:  /contact
    defaults: { _controller: DistribuceTiskuBundle:Page:contact }
    requirements:   
        _method: GET|POST       


_seznamTiskovin:    
    pattern:  /seznamTiskovin
    defaults: { _controller: DistribuceTiskuBundle:Page:seznamTiskovin }
    requirements:   
        _method: GET
        
_login:
    path:   /login
    defaults:  { _controller: DistribuceTiskuBundle:Security:login }

_login_check:
    path:   /login_check
    defaults:  { _controller: DistribuceTiskuBundle:Security:login_check }
    
_logout:
    path:   /logout
    defaults:  { _controller: DistribuceTiskuBundle:Security:logout }
    
_customerAdd:    
    pattern:  /customerAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:customeradd }
    requirements:   
        _method: GET|POST
        
_customerEdit:    
    pattern:  /customerAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:customeradd }
    requirements:   
        _method: GET|POST
        
_customerRemove:    
    pattern:  /customerAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:customeradd }
    requirements:   
        _method: GET|POST        
        
_bookAdd:    
    pattern:  /bookAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:bookadd }
    requirements:   
        _method: GET|POST
        
_supplierAdd:    
    pattern:  /supplierAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:supplieradd }
    requirements:   
        _method: GET|POST
        
_subscriptionAdd:    
    pattern:  /subscriptionAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionadd }
    requirements:   
        _method: GET|POST
        
_subscriptionInteruptionAdd:    
    pattern:  /subscriptionInteruptionAdd
    defaults: { _controller: DistribuceTiskuBundle:Form:subscriptionInteruptionadd }
    requirements:   
        _method: GET|POST