parameters:
#    distribuce_tisku.example.class: DistribuceTisku\Bundle\Example


services:
    acme.twig.acme_extension:
        class: DistribuceTisku\Bundle\Twig\AcmeExtension
        tags:
            - { name: twig.extension }